import React, { useState } from 'react'
import { Button } from './ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog'
import { Video } from 'lucide-react'

// Shows scheduled-interview info (date/time, notes, meeting link) for an application.
// Daily.co links (auto-generated by the backend) are embedded in-app via an iframe
// inside a dialog, since Daily.co rooms are designed to be embedded and allow
// camera/mic access to be granted to the iframe. Manually pasted links (Zoom/Meet/
// Teams etc.) can't reliably be embedded (they block iframes via X-Frame-Options),
// so those just render as a plain "Join meeting" link that opens in a new tab.
const InterviewDetails = ({ interview }) => {
    const [videoCallOpen, setVideoCallOpen] = useState(false);

    if (!interview?.scheduledAt) {
        return null;
    }

    const isDailyRoom = interview.meetingLink?.includes("daily.co");

    return (
        <div className='text-xs text-gray-600 mt-1'>
            <p>Interview: {new Date(interview.scheduledAt).toLocaleString()}</p>
            {
                interview.notes && (
                    <p className='mt-0.5'>Notes: {interview.notes}</p>
                )
            }
            {
                interview.meetingLink && (
                    isDailyRoom ? (
                        <>
                            <Button
                                size="sm"
                                variant="outline"
                                className="mt-1 h-7 gap-1 text-xs"
                                onClick={() => setVideoCallOpen(true)}
                            >
                                <Video className="h-3 w-3" />
                                Join Video Call
                            </Button>
                            <Dialog open={videoCallOpen} onOpenChange={setVideoCallOpen}>
                                <DialogContent className="sm:max-w-[700px]" onInteractOutside={() => setVideoCallOpen(false)}>
                                    <DialogHeader>
                                        <DialogTitle>Video Interview</DialogTitle>
                                    </DialogHeader>
                                    {
                                        videoCallOpen && (
                                            <iframe
                                                src={interview.meetingLink}
                                                allow="camera; microphone; fullscreen; display-capture"
                                                className="w-full h-[500px] rounded-md border"
                                            />
                                        )
                                    }
                                </DialogContent>
                            </Dialog>
                        </>
                    ) : (
                        <a
                            href={interview.meetingLink}
                            target='_blank'
                            rel="noopener noreferrer"
                            className='text-blue-600 hover:underline'
                        >
                            Join meeting
                        </a>
                    )
                )
            }
        </div>
    )
}

export default InterviewDetails
